# Generated by Django 2.2.28 on 2022-12-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221123_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitch',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
